### ISSUE TITLE
Adding nuxt-env to modules results in a 'TypeError: Cannot read property 'length' of undefined' error

### ISSUE THREAD

**Issue by dschreij** [samtgarson/nuxt-env#11]
I am using Nuxt 2.2.0 and nuxt-env 0.0.4

When I add nuxt-env to my modules with

```
  modules: [
    'nuxt-env', {
      keys: ['API_HOST']
    }
  ],
```

`npm run build` fails with the following stacktrace:

```
✖ fatal TypeError: Cannot read property 'length' of undefined
  at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:410:15)
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:20)
  at Nuxt.resolveModule (/Users/daniel/Git/everythingbonaire/app/node_modules/nuxt/dist/nuxt.js:2430:35)
  at Nuxt.resolveAlias (/Users/daniel/Git/everythingbonaire/app/node_modules/nuxt/dist/nuxt.js:2445:29)
  at Nuxt.resolvePath (/Users/daniel/Git/everythingbonaire/app/node_modules/nuxt/dist/nuxt.js:2465:24)
  at Nuxt.requireModule (/Users/daniel/Git/everythingbonaire/app/node_modules/nuxt/dist/nuxt.js:2481:32)
  at ModuleContainer.addModule (/Users/daniel/Git/everythingbonaire/app/node_modules/nuxt/dist/nuxt.js:601:27)
  at promise.then (/Users/daniel/Git/everythingbonaire/app/node_modules/nuxt/dist/nuxt.js:151:43)
  at internalTickCallback (internal/process/next_tick.js:77:7)
  at process._tickCallback (internal/process/next_tick.js:47:5)
  at Function.Module.runMain (internal/modules/cjs/loader.js:763:11)
  at startup (internal/bootstrap/node.js:303:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
```

**Comment by dschreij** [comment]
My bad, the nuxt-env entry must be encapsulated in another array..

WRONG:
```
modules: [
    'nuxt-env', {
      keys: ['API_HOST']
    }
  ]
```
CORRECT:
```
modules: [
    ['nuxt-env', {
      keys: ['API_HOST']
    }]
  ],
```
